"""
Auto-Pauser for VLC
--------------------
Watches all Windows audio sessions EXCEPT VLC's own, and automatically
pauses (or mutes) VLC whenever any other app's audio peak crosses a
threshold. Resumes playback after a period of quiet. Optionally fades
the volume down before pausing/muting, and back up after resuming, so
it doesn't cut off mid-word.

Runs as a system tray icon so it stays out of the way. Two of the tray
menu toggles (fade, mute-instead-of-pause) are remembered across restarts
via a small settings JSON file next to this script/exe.

No manual VLC setup is required. This app talks to VLC over its built-in
HTTP interface, which it enables itself by launching VLC with
"--extraintf http --http-password <auto-generated> --http-port <port>" -
there is nothing to check or configure in VLC's Preferences. The password
is generated once and cached in vlc_config.json next to this script/exe,
alongside VLC's install path and (optionally) a default playlist folder.

If VLC is already running when this starts AND its web interface is
already reachable (e.g. it was started with matching flags previously),
it's left completely alone. Otherwise it's closed and relaunched with the
interface enabled.

Optional launch argument, meant for a shortcut's "Target"/"Arguments" field:

    "<Dir>\\Background-AutoPause.exe" --launchPlaylist "<Playlist Dir>"

When given, VLC opens looped/minimized on that folder instead of empty.
"""

import sys
import os

# --- Suppress console windows from any child process we launch (taskkill,
# VLC, powershell, etc). Only matters once this is compiled with PyInstaller
# in --windowed mode, where there's no console for a child process to
# attach to - without this, each subprocess call would briefly flash a new
# console window. Must be applied before subprocess is used anywhere below.
if sys.platform == "win32":
    import subprocess as _subprocess
    _original_popen_init = _subprocess.Popen.__init__

    def _no_window_popen_init(self, *args, **kwargs):
        kwargs["creationflags"] = kwargs.get("creationflags", 0) | _subprocess.CREATE_NO_WINDOW
        return _original_popen_init(self, *args, **kwargs)

    _subprocess.Popen.__init__ = _no_window_popen_init

import argparse
import ctypes
import queue
import re
import secrets
import shutil
import subprocess
import threading
import time
import base64
import urllib.request
import urllib.error
import json
import logging
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from logging.handlers import RotatingFileHandler

import comtypes
from pycaw.pycaw import AudioUtilities, IAudioMeterInformation
import pystray
from PIL import Image, ImageDraw

if sys.platform == "win32":
    import winreg
    from ctypes import wintypes

# ----------------------------------------------------------------------
# CONFIG - edit these to taste
# ----------------------------------------------------------------------
VLC_HOST = "localhost"          # VLC's web interface is only ever bound
                                 # to localhost - see ensure_vlc_ready()

THRESHOLD = 0.06                   # 0.0 - 1.0 peak level that counts as "sound"
CHECK_INTERVAL = 0.05              # seconds between volume checks
PAUSE_AFTER = 0.5                 # seconds of sustained sound before pausing
RESUME_AFTER = 0.6                 # seconds of sustained quiet before resuming
LOUD_HOLD = 0.5                    # treat sound as "still present" for this many
                                    # seconds after the last loud reading - smooths
                                    # over natural micro-gaps in a peak meter

FADE_TIME = 0.6                    # seconds to fade volume in/out, typically 0.5-1.0.
                                    # <= 0 always falls back to an instant cutoff,
                                    # regardless of the tray "Fade" toggle.
VLC_FULL_VOLUME = 256              # VLC's HTTP volume scale: 256 = 100%

EXCLUDE_PROCESS_NAMES = {"vlc.exe"}

DEBUG = False                      # prints/logs live peak readings
                                    # set to True again if you need to troubleshoot
# ----------------------------------------------------------------------

# Settings/config live next to the .exe once this is compiled with
# PyInstaller (onedir build), or next to this .py file when run from
# source - either way, "next to the running app" rather than some fixed
# install path, so a portable copy just works.
if getattr(sys, "frozen", False):
    BASE_DIR = os.path.dirname(sys.executable)
else:
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))

SETTINGS_FILE = os.path.join(BASE_DIR, "auto_pauser_settings.json")
DEFAULT_SETTINGS = {"fade_enabled": True, "mute_mode": False}

VLC_CONFIG_FILE = os.path.join(BASE_DIR, "vlc_config.json")
DEFAULT_VLC_CONFIG = {
    "vlc_path": r"C:\Program Files\VideoLAN\VLC\vlc.exe",
    "default_playlist": "",
    "http_port": 8080,
    "http_password": "",   # auto-generated on first run - see load_vlc_config()
}

LOG_FILE = os.path.join(BASE_DIR, "auto_pauser.log")

SINGLE_INSTANCE_MUTEX_NAME = "Global\\BGM_AutoPauser_SingleInstance"


# ----------------------------------------------------------------------
# Logging - only really matters once this is a --windowed frozen exe,
# where there's no console for print()/DEBUG output or an unhandled
# crash traceback to land on. Kept lightweight; disabled cleanly if the
# log file can't be created for some reason (e.g. a read-only folder).
# ----------------------------------------------------------------------
def _setup_logging():
    try:
        handler = RotatingFileHandler(LOG_FILE, maxBytes=1_000_000, backupCount=2, encoding="utf-8")
        handler.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(message)s"))
        root = logging.getLogger()
        root.setLevel(logging.DEBUG if DEBUG else logging.INFO)
        root.addHandler(handler)
    except OSError:
        pass


class _StreamToLogger:
    """Stand-in for sys.stdout/sys.stderr when frozen+windowed, where
    both are None and a bare print() would raise. Routes writes to the
    log file line-by-line instead."""

    def __init__(self, level):
        self.level = level
        self._buffer = ""

    def write(self, message):
        self._buffer += message
        while "\n" in self._buffer:
            line, self._buffer = self._buffer.split("\n", 1)
            if line.strip():
                logging.log(self.level, line)

    def flush(self):
        pass

    def isatty(self):
        return False


if getattr(sys, "frozen", False):
    _setup_logging()
    sys.stdout = _StreamToLogger(logging.INFO)
    sys.stderr = _StreamToLogger(logging.ERROR)
    logging.info("=== Auto-Pauser starting (frozen build) ===")


def load_settings():
    try:
        with open(SETTINGS_FILE, "r") as f:
            data = json.load(f)
        return {**DEFAULT_SETTINGS, **{k: data[k] for k in DEFAULT_SETTINGS if k in data}}
    except (FileNotFoundError, json.JSONDecodeError, OSError, ValueError):
        return dict(DEFAULT_SETTINGS)


def save_settings(settings):
    try:
        with open(SETTINGS_FILE, "w") as f:
            json.dump(settings, f, indent=2)
    except OSError as e:
        if DEBUG:
            print(f"[settings] failed to save: {e}")


# ----------------------------------------------------------------------
# VLC install-location + connection config
# ----------------------------------------------------------------------
def load_vlc_config():
    """Reads vlc_config.json next to the app, creating it with sane
    defaults on first run (including a freshly generated http_password)
    so there's nothing for the user to fill in before things work."""
    try:
        with open(VLC_CONFIG_FILE, "r") as f:
            data = json.load(f)
        cfg = {**DEFAULT_VLC_CONFIG, **{k: data[k] for k in DEFAULT_VLC_CONFIG if k in data}}
    except (FileNotFoundError, json.JSONDecodeError, OSError, ValueError):
        cfg = dict(DEFAULT_VLC_CONFIG)

    needs_save = not os.path.isfile(VLC_CONFIG_FILE)
    if not cfg.get("http_password"):
        cfg["http_password"] = secrets.token_hex(12)
        needs_save = True
    if needs_save:
        save_vlc_config(cfg)

    return cfg


def save_vlc_config(cfg):
    try:
        with open(VLC_CONFIG_FILE, "w") as f:
            json.dump(cfg, f, indent=2)
    except OSError as e:
        if DEBUG:
            print(f"[vlc_config] failed to save: {e}")


def _which_vlc():
    return shutil.which("vlc") or shutil.which("vlc.exe")


def _detect_vlc_via_registry():
    """VLC's installer writes its install folder to the registry - this is
    the most reliable way to find it regardless of drive/folder choice."""
    if sys.platform != "win32":
        return None
    reg_locations = [
        (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\VideoLAN\VLC"),
        (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\VideoLAN\VLC"),
        (winreg.HKEY_CURRENT_USER, r"SOFTWARE\VideoLAN\VLC"),
    ]
    for hive, subkey in reg_locations:
        try:
            with winreg.OpenKey(hive, subkey) as key:
                install_dir, _ = winreg.QueryValueEx(key, "InstallDir")
                candidate = os.path.join(install_dir, "vlc.exe")
                if os.path.isfile(candidate):
                    return candidate
        except OSError:
            continue
    return None


def _detect_vlc_via_common_paths():
    for candidate in (
        r"C:\Program Files\VideoLAN\VLC\vlc.exe",
        r"C:\Program Files (x86)\VideoLAN\VLC\vlc.exe",
    ):
        if os.path.isfile(candidate):
            return candidate
    return None


def resolve_vlc_path():
    """Priority: an explicit, still-valid path in vlc_config.json, then
    dynamic detection (PATH -> registry -> common install folders). A
    freshly detected path is written back to the json so it stays in sync
    if VLC gets reinstalled/moved. Returns None if nothing at all is found."""
    cfg = load_vlc_config()
    configured = (cfg.get("vlc_path") or "").strip()

    if configured and os.path.isfile(configured):
        return configured

    detected = _which_vlc() or _detect_vlc_via_registry() or _detect_vlc_via_common_paths()
    if detected:
        if detected != configured:
            cfg["vlc_path"] = detected
            save_vlc_config(cfg)
        return detected

    if configured:
        logging.warning(f"[vlc] configured vlc_path does not exist: {configured}")
        return configured  # let the launch attempt fail loudly/log it, rather than guess further

    logging.warning("[vlc] could not locate vlc.exe anywhere")
    return None


# ----------------------------------------------------------------------
# Playlist shortcuts - one .exe can only ever have one Start Menu shortcut
# with one fixed set of Arguments, so multiple looped-playlist "profiles"
# (e.g. one shortcut per music folder) need one shortcut each, each with
# its own --launchPlaylist. This builds those on demand from the tray menu:
# a small .bat under playlist-shortcuts/_bats/ that calls this app with the
# chosen playlist baked in, and a .lnk under playlist-shortcuts/ pointing at
# that .bat - so the shortcuts are easy to find, rename, or delete later
# without touching this app's own folder.
# ----------------------------------------------------------------------
SHORTCUTS_DIR = os.path.join(BASE_DIR, "playlist-shortcuts")
SHORTCUTS_BATS_DIR = os.path.join(SHORTCUTS_DIR, "_bats")

_INVALID_FILENAME_CHARS = re.compile(r'[<>:"/\\|?*\x00-\x1f]')


def _sanitize_filename(name):
    name = _INVALID_FILENAME_CHARS.sub("", name).strip()
    name = name.rstrip(" .")  # Windows disallows trailing dots/spaces in filenames
    return name or "Playlist"


def _unique_path(path):
    """Appends ' (2)', ' (3)', etc. if path already exists, rather than
    silently overwriting an existing same-named shortcut."""
    if not os.path.exists(path):
        return path
    base, ext = os.path.splitext(path)
    n = 2
    while True:
        candidate = f"{base} ({n}){ext}"
        if not os.path.exists(candidate):
            return candidate
        n += 1


def _ps_quote(value):
    """Single-quotes a value for embedding in a PowerShell script,
    doubling any embedded single quotes (PowerShell's own escape rule)."""
    return "'" + str(value).replace("'", "''") + "'"


def create_playlist_shortcut(playlist_dir, name, pin_to_start):
    """Creates a direct .lnk shortcut pointing directly to the application 
    executable with the --launchPlaylist argument included, bypassing the 
    need for any intermediate .bat files."""
    os.makedirs(SHORTCUTS_DIR, exist_ok=True)

    safe_name = _sanitize_filename(name)
    lnk_path = _unique_path(os.path.join(SHORTCUTS_DIR, safe_name + ".lnk"))

    # Determine what the base application is (the compiled exe or python interpreter)
    if getattr(sys, "frozen", False):
        target_exe = sys.executable
        arguments = f'--launchPlaylist "{playlist_dir}"'
    else:
        # Running from source code (.py file)
        target_exe = sys.executable
        arguments = f'"{os.path.abspath(__file__)}" --launchPlaylist "{playlist_dir}"'

    ps_lines = [
        "$s = New-Object -ComObject WScript.Shell",
        f"$sc = $s.CreateShortcut({_ps_quote(lnk_path)})",
        f"$sc.TargetPath = {_ps_quote(target_exe)}",
        f"$sc.Arguments = {_ps_quote(arguments)}",
        f"$sc.WorkingDirectory = {_ps_quote(BASE_DIR)}",
        f"$sc.IconLocation = {_ps_quote(target_exe + ',0')}",
        "$sc.Save()",
    ]
    if pin_to_start:
        # Best-effort attempt to pin the shortcut directly to the Start Menu
        ps_lines += [
            "try {",
            "  $shellApp = New-Object -ComObject Shell.Application",
            f"  $folder = $shellApp.Namespace({_ps_quote(SHORTCUTS_DIR)})",
            f"  $item = $folder.ParseName({_ps_quote(os.path.basename(lnk_path))})",
            "  $item.InvokeVerb('pintostartscreen')",
            "} catch {}",
        ]

    script = "\n".join(ps_lines)
    encoded = base64.b64encode(script.encode("utf-16-le")).decode("ascii")
    result = subprocess.run(
        ["powershell", "-NoProfile", "-NonInteractive", "-EncodedCommand", encoded],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or "PowerShell shortcut creation failed")

    return lnk_path



def _reveal_in_explorer(path):
    try:
        # Correct form: /select, as its own token, path as the following argument.
        # Explorer's command-line parser is extremely picky; the old
        # f'/select,"{path}"' single-token form often fails and falls back
        # to the user's Documents folder.
        subprocess.run(["explorer", "/select,", os.path.normpath(path)], check=False)
    except Exception as e:
        if DEBUG:
            print(f"[shortcut] failed to open Explorer: {e}")


def _ask_shortcut_details(root, default_name):
    """Small modal dialog: shortcut name + Pin to Start checkbox.
    Returns (name, pin_to_start), or None if cancelled."""
    dialog = tk.Toplevel(root)
    dialog.title("New Playlist Shortcut")
    dialog.resizable(False, False)
    dialog.attributes("-topmost", True)
    result = {"value": None}

    tk.Label(dialog, text="Shortcut name:").grid(row=0, column=0, columnspan=2, sticky="w", padx=12, pady=(12, 0))
    name_var = tk.StringVar(value=default_name)
    entry = tk.Entry(dialog, textvariable=name_var, width=34)
    entry.grid(row=1, column=0, columnspan=2, padx=12, pady=(2, 10))
    entry.focus_set()
    entry.select_range(0, "end")

    pin_var = tk.BooleanVar(value=True)
    tk.Checkbutton(dialog, text="Open Shortcut Location", variable=pin_var).grid(
        row=2, column=0, columnspan=2, sticky="w", padx=12
    )

    def on_ok(event=None):
        result["value"] = (name_var.get().strip(), pin_var.get())
        dialog.destroy()

    def on_cancel(event=None):
        result["value"] = None
        dialog.destroy()

    btns = tk.Frame(dialog)
    btns.grid(row=3, column=0, columnspan=2, pady=12)
    tk.Button(btns, text="Create", command=on_ok, width=10, default="active").pack(side="left", padx=5)
    tk.Button(btns, text="Cancel", command=on_cancel, width=10).pack(side="left", padx=5)

    dialog.bind("<Return>", on_ok)
    dialog.bind("<Escape>", on_cancel)
    dialog.protocol("WM_DELETE_WINDOW", on_cancel)

    dialog.update_idletasks()
    w, h = dialog.winfo_width(), dialog.winfo_height()
    sw, sh = dialog.winfo_screenwidth(), dialog.winfo_screenheight()
    dialog.geometry(f"+{(sw - w) // 2}+{(sh - h) // 2}")

    dialog.grab_set()
    dialog.wait_window()

    if not result["value"] or not result["value"][0]:
        return None
    return result["value"]


def _new_playlist_shortcut_flow(root):
    """Runs entirely on the Tk thread: folder picker -> name/pin dialog ->
    create the shortcut -> confirm (and open Explorer with it selected, so
    Pin to Start can be finished by hand if the automatic attempt didn't
    take - see create_playlist_shortcut())."""
    playlist_dir = filedialog.askdirectory(title="Choose the playlist folder for this shortcut", mustexist=True)
    if not playlist_dir:
        return
    playlist_dir = os.path.normpath(playlist_dir)

    details = _ask_shortcut_details(root, default_name=os.path.basename(playlist_dir) or "Playlist")
    if details is None:
        return
    name, pin_to_start = details

    try:
        lnk_path = create_playlist_shortcut(playlist_dir, name, pin_to_start)
    except Exception as e:
        logging.error(f"[shortcut] failed to create playlist shortcut: {e}")
        messagebox.showerror("Shortcut creation failed", f"Something went wrong:\n{e}")
        return

    _reveal_in_explorer(lnk_path)
    note = (
        "\n\nA \"Pin to Start\" attempt was made, but Windows doesn't always "
        "allow this - if it didn't show up, right-click the shortcut "
        "(now selected in Explorer) and choose Pin to Start yourself."
        if pin_to_start else ""
    )


def ensure_vlc_ready(controller, vlc_cfg, playlist):
    """Makes sure VLC is reachable over the HTTP interface, without ever
    touching VLC's own Preferences.

    If a working web interface is already reachable (matching password),
    VLC is left completely alone - covers the case where it's already
    running from a previous launch, or from a shortcut the user set up
    with matching --http-password/--http-port flags of their own.

    Otherwise, any running VLC is closed and a fresh one launched with
    the web interface baked into the command line
    (--extraintf http --http-password ... --http-port ...), so nothing
    needs to be configured by hand.
    """
    if controller.status() is not None:
        logging.info("[vlc] web interface already reachable - leaving the running VLC alone")
        return

    vlc_path = resolve_vlc_path()

    try:
        subprocess.run(
            ["taskkill", "/f", "/im", "vlc.exe"],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )
    except Exception as e:
        if DEBUG:
            print(f"[vlc] taskkill failed (probably wasn't running): {e}")
    time.sleep(0.5)

    if not vlc_path:
        logging.error("[vlc] no VLC install found - can't launch it. "
                       "Set \"vlc_path\" in vlc_config.json manually.")
        return

    launch_args = [
        vlc_path,
        "--extraintf", "http",
        "--http-host", VLC_HOST,
        "--http-port", str(vlc_cfg.get("http_port", 8080)),
        "--http-password", vlc_cfg.get("http_password", ""),
        "--qt-start-minimized",
    ]
    if playlist:
        launch_args += ["--loop", playlist]

    try:
        subprocess.Popen(launch_args)
        logging.info(f"[vlc] launched with web interface enabled (playlist={playlist!r})")
    except OSError as e:
        logging.error(f"[vlc] failed to launch '{vlc_path}': {e}")


# ----------------------------------------------------------------------
# Single instance - relaunching the shortcut (e.g. with a different
# --launchPlaylist) should behave like a clean restart, not stack up a
# second tray icon and a second audio-watching loop.
# ----------------------------------------------------------------------
def ensure_single_instance():
    if sys.platform != "win32":
        return None

    kernel32 = ctypes.windll.kernel32
    mutex = kernel32.CreateMutexW(None, False, SINGLE_INSTANCE_MUTEX_NAME)
    ERROR_ALREADY_EXISTS = 183
    if ctypes.GetLastError() == ERROR_ALREADY_EXISTS:
        try:
            if getattr(sys, "frozen", False):
                # The frozen exe has a distinctive process image name, so a
                # plain taskkill-by-name (excluding our own new PID) works.
                exe_name = os.path.basename(sys.executable)
                subprocess.run(
                    ["taskkill", "/f", "/im", exe_name, "/fi", f"PID ne {os.getpid()}"],
                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                )
            else:
                # Running from source, the process image name is just
                # "python.exe" - too generic to taskkill by name safely (it'd
                # risk killing unrelated Python processes). Match by command
                # line instead, same approach the old run_auto_pauser.bat used.
                script_name = os.path.basename(__file__)
                ps_cmd = (
                    f"Get-CimInstance Win32_Process -Filter \"CommandLine LIKE '%{script_name}%'\" "
                    f"| Where-Object ProcessId -ne {os.getpid()} | Remove-CimInstance"
                )
                subprocess.run(
                    ["powershell", "-NoProfile", "-Command", ps_cmd],
                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                )
        except Exception as e:
            if DEBUG:
                print(f"[instance] failed to close previous instance: {e}")
        time.sleep(1)
    return mutex  # kept referenced for the process lifetime; not otherwise used


class VLCController:
    """Talks to VLC's built-in HTTP interface."""

    def __init__(self, host, port, password):
        self.base_url = f"http://{host}:{port}/requests"
        auth = base64.b64encode(f":{password}".encode()).decode()
        self.headers = {"Authorization": f"Basic {auth}"}

    def _get(self, path, retries=1):
        req = urllib.request.Request(self.base_url + path, headers=self.headers)
        for attempt in range(retries + 1):
            try:
                with urllib.request.urlopen(req, timeout=3.0) as resp:
                    data = resp.read()
                    if DEBUG:
                        print(f"[vlc] GET {path} -> HTTP {resp.status}")
                    return data
            except urllib.error.HTTPError as e:
                if DEBUG:
                    print(f"[vlc] HTTP error {e.code} for {path}")
                return None
            except (urllib.error.URLError, ConnectionError, TimeoutError) as e:
                if DEBUG:
                    print(f"[vlc] connection error for {path} (attempt {attempt + 1}): {e}")
        return None

    def _status_dict(self):
        data = self._get("/status.json")
        if data is None:
            return None
        try:
            return json.loads(data)
        except json.JSONDecodeError:
            if DEBUG:
                print("[vlc] failed to parse status response")
            return None

    def status(self):
        """Returns 'playing', 'paused', 'stopped', or None if VLC/web iface unreachable."""
        d = self._status_dict()
        return d.get("state") if d else None

    def get_volume(self):
        """Returns the current volume on VLC's 0-256(+) scale, or None if unreachable."""
        d = self._status_dict()
        if d and "volume" in d:
            return d["volume"]
        return None

    def set_volume(self, val):
        val = max(0, int(round(val)))
        self._get(f"/status.json?command=volume&val={val}")

    def pause(self):
        st = self.status()
        if DEBUG:
            print(f"[vlc] pause() called - current VLC status: {st}")
        if st == "playing":
            self._get("/status.json?command=pl_forcepause")

    def play(self):
        st = self.status()
        if DEBUG:
            print(f"[vlc] play() called - current VLC status: {st}")
        if st == "paused":
            self._get("/status.json?command=pl_forceresume")


def get_other_audio_peak():
    """Returns the max peak level (0.0-1.0) across all sessions except excluded ones."""
    peak = 0.0
    try:
        sessions = AudioUtilities.GetAllSessions()
    except Exception as e:
        if DEBUG:
            print(f"[debug] GetAllSessions failed: {e}")
        return 0.0

    for session in sessions:
        if session.Process is None:
            continue
        name = session.Process.name().lower()
        if name in EXCLUDE_PROCESS_NAMES:
            continue
        try:
            meter = session._ctl.QueryInterface(IAudioMeterInformation)
            level = meter.GetPeakValue()
            if level > peak:
                peak = level
        except Exception as e:
            if DEBUG:
                print(f"[debug] peak read failed for {name}: {e}")
            continue
    return peak


class AutoPauser:
    def __init__(self, vlc_controller: "VLCController"):
        self.vlc = vlc_controller
        self.enabled = True

        settings = load_settings()
        self.fade_enabled = settings["fade_enabled"]
        self.mute_mode = settings["mute_mode"]

        self._stop = False
        self._sound_since = None
        self._quiet_since = None
        self._last_loud_at = None

        self._ducked = False           # True while paused/muted by us
        self._fade_state = None        # None, "out", or "in"
        self._fade_start_time = None
        self._fade_start_vol = None
        self._original_volume = None   # volume level to fade back up to / restore

    def _save_settings(self):
        save_settings({"fade_enabled": self.fade_enabled, "mute_mode": self.mute_mode})

    def loop(self):
        # pycaw talks to Windows' COM-based audio API, which requires each
        # thread that uses it to initialize its own COM apartment - without
        # this, calls made from this background thread fail silently and
        # get_other_audio_peak() would always report 0.
        comtypes.CoInitialize()
        try:
            while not self._stop:
                if self.enabled:
                    self._tick()
                time.sleep(CHECK_INTERVAL)
        finally:
            comtypes.CoUninitialize()

    def _fade_is_effective(self):
        return self.fade_enabled and FADE_TIME > 0

    def _begin_duck(self):
        """Start pausing/muting - either straight away, or by kicking off a fade-out."""
        if DEBUG:
            action = "muting" if self.mute_mode else "pausing"
            print(f"[auto-pauser] threshold sustained -> {action}")

        vol = self.vlc.get_volume()
        if vol is not None:
            self._original_volume = vol
        elif self._original_volume is None:
            self._original_volume = VLC_FULL_VOLUME

        if self._fade_is_effective():
            self._fade_state = "out"
            self._fade_start_time = time.time()
            self._fade_start_vol = self._original_volume
        else:
            if self.mute_mode:
                self.vlc.set_volume(0)
            else:
                self.vlc.pause()

        self._ducked = True

    def _begin_undock(self):
        """Start resuming/unmuting - either straight away, or by kicking off a fade-in."""
        if DEBUG:
            action = "unmuting" if self.mute_mode else "resuming"
            print(f"[auto-pauser] quiet sustained -> {action}")

        if not self.mute_mode:
            # Playback needs to actually resume before/while the volume ramps
            # back up - otherwise there's nothing to fade in.
            self.vlc.play()

        if self._fade_is_effective():
            self._fade_state = "in"
            self._fade_start_time = time.time()
            self._fade_start_vol = 0
        elif self.mute_mode:
            target = self._original_volume if self._original_volume is not None else VLC_FULL_VOLUME
            self.vlc.set_volume(target)
        # non-mute, non-fade: pause()/play() alone already covers it.

        self._ducked = False

    def _advance_fade(self, now):
        elapsed = now - self._fade_start_time
        progress = min(1.0, elapsed / FADE_TIME)
        target = self._original_volume if self._original_volume is not None else VLC_FULL_VOLUME

        if self._fade_state == "out":
            vol = self._fade_start_vol * (1 - progress)
            self.vlc.set_volume(vol)
            if progress >= 1.0:
                self.vlc.set_volume(0)
                if not self.mute_mode:
                    self.vlc.pause()
                self._fade_state = None
        elif self._fade_state == "in":
            vol = target * progress
            self.vlc.set_volume(vol)
            if progress >= 1.0:
                self.vlc.set_volume(target)
                self._fade_state = None

    def _tick(self):
        peak = get_other_audio_peak()
        now = time.time()

        if DEBUG:
            self._debug_counter = getattr(self, "_debug_counter", 0) + 1
            if self._debug_counter % 10 == 0:  # roughly every ~1.5s
                bar = "#" * int(peak * 40)
                print(f"peak={peak:.3f} threshold={THRESHOLD} {bar}")

        if peak >= THRESHOLD:
            self._last_loud_at = now

        is_loud = self._last_loud_at is not None and (now - self._last_loud_at) <= LOUD_HOLD

        if self._fade_state is not None:
            self._advance_fade(now)

        if is_loud:
            self._quiet_since = None
            if self._sound_since is None:
                self._sound_since = now
            elif (
                not self._ducked
                and self._fade_state is None
                and (now - self._sound_since) >= PAUSE_AFTER
            ):
                self._begin_duck()
        else:
            self._sound_since = None
            if self._quiet_since is None:
                self._quiet_since = now
            elif (
                self._ducked
                and self._fade_state is None
                and (now - self._quiet_since) >= RESUME_AFTER
            ):
                self._begin_undock()

    def stop(self):
        self._stop = True

    def disable(self):
        """Manual 'Enabled' toggle turning OFF - stops the watcher AND
        immediately pauses/mutes VLC's current track, so switching this off
        actually silences things instead of leaving the watcher's last state
        in place until something happens to change it."""
        self.enabled = False
        self._fade_state = None
        if self.mute_mode:
            vol = self.vlc.get_volume()
            if vol is not None:
                self._original_volume = vol
            elif self._original_volume is None:
                self._original_volume = VLC_FULL_VOLUME
            self.vlc.set_volume(0)
        else:
            self.vlc.pause()
        self._ducked = True

    def enable(self):
        """Manual 'Enabled' toggle turning back ON - resumes/unmutes VLC
        immediately and resets the watcher's timers so it starts fresh (if
        other audio is still loud, it'll naturally re-pause within
        PAUSE_AFTER seconds, same as any other time it detects noise)."""
        self.enabled = True
        self._sound_since = None
        self._quiet_since = None
        self._last_loud_at = None
        self._fade_state = None
        if self.mute_mode:
            target = self._original_volume if self._original_volume is not None else VLC_FULL_VOLUME
            self.vlc.set_volume(target)
        else:
            self.vlc.play()
        self._ducked = False


def make_icon_image(color):
    img = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.ellipse((8, 8, 56, 56), fill=color)
    return img


# ----------------------------------------------------------------------
# Volume slider popup
# ----------------------------------------------------------------------
# A right-click tray menu can only ever hold text items/checkboxes - Windows'
# shell context menus have no slider control, so "a slider in the tray" is
# actually a small standalone window that appears next to where you clicked,
# same trick Windows' own volume/brightness flyouts use. It needs a Tk
# mainloop, which has to run on the main thread - so pystray's message loop
# (normally the thing blocking main()) is moved to a background thread
# instead, and the two talk to each other via a thread-safe queue rather
# than calling into Tk directly from pystray's thread.
_VOLUME_POPUP_SIZE = (220, 78)


def _get_cursor_pos():
    pt = wintypes.POINT()
    ctypes.windll.user32.GetCursorPos(ctypes.byref(pt))
    return pt.x, pt.y


def _show_volume_popup(root, vlc: "VLCController"):
    current = vlc.get_volume()
    percent = int(round((current / VLC_FULL_VOLUME) * 100)) if current is not None else 100
    percent = max(0, min(100, percent))

    popup = tk.Toplevel(root)
    popup.overrideredirect(True)      # no titlebar/border - this is a flyout, not a window
    popup.attributes("-topmost", True)
    popup.configure(bg="#2b2b2b")

    width, height = _VOLUME_POPUP_SIZE
    cursor_x, cursor_y = _get_cursor_pos()
    x = max(0, cursor_x - width // 2)
    y = max(0, cursor_y - height - 12)  # open above the click, like the menu that spawned it
    popup.geometry(f"{width}x{height}+{x}+{y}")

    tk.Label(
        popup, text="VLC Volume", fg="white", bg="#2b2b2b", font=("Segoe UI", 9)
    ).pack(pady=(8, 0))

    pct_var = tk.StringVar(value=f"{percent}%")
    last_sent_at = [0.0]
    MIN_SEND_INTERVAL = 0.05  # throttle mid-drag HTTP calls to ~20/sec

    def send_volume(pct):
        vlc.set_volume(pct / 100 * VLC_FULL_VOLUME)

    def on_change(raw_value):
        pct = int(float(raw_value))
        pct_var.set(f"{pct}%")
        now = time.time()
        if now - last_sent_at[0] >= MIN_SEND_INTERVAL:
            send_volume(pct)
            last_sent_at[0] = now

    def on_release(_event):
        send_volume(int(float(scale.get())))  # make sure the final position always lands

    row = tk.Frame(popup, bg="#2b2b2b")
    row.pack(padx=16, pady=(4, 0), fill="x")

    scale = ttk.Scale(row, from_=0, to=100, orient="horizontal", command=on_change, length=150)
    scale.set(percent)
    scale.pack(side="left", fill="x", expand=True)
    scale.bind("<ButtonRelease-1>", on_release)

    tk.Label(row, textvariable=pct_var, fg="white", bg="#2b2b2b", font=("Segoe UI", 9), width=4).pack(
        side="left", padx=(6, 0)
    )

    # Clicking elsewhere closes it, same as any other flyout
    popup.bind("<FocusOut>", lambda e: popup.destroy())
    popup.focus_force()


def _tk_ui_loop(ui_queue: "queue.Queue", pauser: AutoPauser):
    """Runs on the main thread. Owns the (hidden) Tk root and processes
    requests - opening the volume popup, shutting down - posted from the
    pystray thread via ui_queue, so pystray's own thread never touches
    Tk objects directly."""
    root = tk.Tk()
    root.withdraw()  # this root window itself is never shown - only its Toplevel popups are

    def poll_queue():
        try:
            while True:
                msg = ui_queue.get_nowait()
                if msg == "volume":
                    _show_volume_popup(root, pauser.vlc)
                elif msg == "new_shortcut":
                    _new_playlist_shortcut_flow(root)
                elif msg == "quit":
                    root.quit()
                    return
        except queue.Empty:
            pass
        root.after(100, poll_queue)

    root.after(100, poll_queue)
    root.mainloop()


def run_tray(pauser: AutoPauser, ui_queue: "queue.Queue"):
    icon_on = make_icon_image((40, 180, 99, 255))
    icon_off = make_icon_image((150, 150, 150, 255))

    def toggle_enabled(icon, item):
        if pauser.enabled:
            pauser.disable()
        else:
            pauser.enable()
        icon.icon = icon_on if pauser.enabled else icon_off
        icon.title = "Auto-Pauser: ON" if pauser.enabled else "Auto-Pauser: OFF (paused)"

    def toggle_fade(icon, item):
        pauser.fade_enabled = not pauser.fade_enabled
        pauser._save_settings()

    def toggle_mute_mode(icon, item):
        pauser.mute_mode = not pauser.mute_mode
        pauser._save_settings()

    def open_volume(icon, item):
        ui_queue.put("volume")

    def new_shortcut(icon, item):
        ui_queue.put("new_shortcut")

    def quit_app(icon, item):
        pauser.stop()
        icon.stop()
        ui_queue.put("quit")

    def quit_app_and_vlc(icon, item):
        try:
            subprocess.run(
                ["taskkill", "/f", "/im", "vlc.exe"],
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            )
        except Exception as e:
            if DEBUG:
                print(f"[quit] failed to close VLC: {e}")
        pauser.stop()
        icon.stop()
        ui_queue.put("quit")

    icon = pystray.Icon(
        "auto_pauser",
        icon_on,
        "Auto-Pauser: ON",
        menu=pystray.Menu(
            pystray.MenuItem(
                "Enabled",
                toggle_enabled,
                checked=lambda item: pauser.enabled,
            ),
            pystray.MenuItem(
                "Fade in/out",
                toggle_fade,
                checked=lambda item: pauser.fade_enabled,
            ),
            pystray.MenuItem(
                "Mute instead of pause",
                toggle_mute_mode,
                checked=lambda item: pauser.mute_mode,
            ),
            pystray.MenuItem("Volume...", open_volume),
            pystray.MenuItem("New Playlist Shortcut...", new_shortcut),
            pystray.Menu.SEPARATOR,
            pystray.MenuItem("Quit", quit_app),
            pystray.MenuItem("Close BGM-AutoPause && VLC", quit_app_and_vlc),
        ),
    )
    icon.run()


def parse_args():
    parser = argparse.ArgumentParser(description="BGM Auto-Pauser for VLC")
    parser.add_argument(
        "--launchPlaylist",
        dest="playlist",
        default=None,
        help="Optional folder VLC should open (looped, minimized) on startup.",
    )
    args, _unknown = parser.parse_known_args()
    return args


def main():
    args = parse_args()

    # Relaunching the shortcut (possibly with a different playlist) should
    # behave like a clean restart rather than piling up tray icons.
    ensure_single_instance()

    vlc_cfg = load_vlc_config()
    controller = VLCController(VLC_HOST, vlc_cfg.get("http_port", 8080), vlc_cfg.get("http_password", ""))

    playlist = (args.playlist or vlc_cfg.get("default_playlist") or "").strip() or None
    ensure_vlc_ready(controller, vlc_cfg, playlist)

    pauser = AutoPauser(controller)
    t = threading.Thread(target=pauser.loop, daemon=True)
    t.start()

    # pystray's message loop and Tk's mainloop each need to own a thread of
    # their own; Tk needs the main thread, so pystray's runs in the
    # background instead, coordinating through ui_queue (see run_tray/_tk_ui_loop).
    ui_queue = queue.Queue()
    tray_thread = threading.Thread(target=run_tray, args=(pauser, ui_queue), daemon=True)
    tray_thread.start()

    _tk_ui_loop(ui_queue, pauser)
    sys.exit(0)


if __name__ == "__main__":
    main()