"""
Auto-Pauser for VLC
--------------------
Watches all Windows audio sessions EXCEPT VLC's own, and automatically
pauses (or mutes) VLC whenever any other app's audio peak crosses a
threshold. Resumes playback after a period of quiet. Optionally fades
the volume down before pausing/muting, and back up after resuming, so
it doesn't cut off mid-word.

Runs as a system tray icon so it stays out of the way. Two of the tray
menu toggles (fade, mute-instead-of-pause) are remembered across restarts
via a small settings JSON file next to this script/exe.

No manual VLC setup is required. This app talks to VLC over its built-in
HTTP interface, which it enables itself by launching VLC with
"--extraintf http --http-password <auto-generated> --http-port <port>" -
there is nothing to check or configure in VLC's Preferences. The password
is generated once and cached in vlc_config.json next to this script/exe,
alongside VLC's install path and (optionally) a default playlist folder.

If VLC is already running when this starts AND its web interface is
already reachable (e.g. it was started with matching flags previously),
it's left completely alone. Otherwise it's closed and relaunched with the
interface enabled.

Optional launch arguments, meant for a shortcut's "Target"/"Arguments" field:

    "<Dir>\\BGM-AutoPauser.exe" --launchPlaylist "<Playlist Dir>"
    "<Dir>\\BGM-AutoPauser.exe" --launchVideoStream "<Stream URL>" [--popout]

--launchPlaylist opens VLC looped/minimized on that folder instead of empty.

--launchVideoStream instead opens VLC windowed (visible in the taskbar) on
that stream URL, and forces "Mute instead of pause" on for the session
(without touching the saved preference used by --launchPlaylist runs) since
pausing a live stream is more likely to cause problems than muting it.
Add --popout to also pop the video out into a sizeable, always-on-top
window. Both of these tray-manageable shortcuts can be created from the
system tray menu ("New Playlist Shortcut..." / "Add Video Stream
Shortcut...") rather than built by hand.
"""

import sys
import os

# --- Suppress console windows from any child process we launch (taskkill,
# VLC, powershell, etc). Only matters once this is compiled with PyInstaller
# in --windowed mode, where there's no console for a child process to
# attach to - without this, each subprocess call would briefly flash a new
# console window. Must be applied before subprocess is used anywhere below.
if sys.platform == "win32":
    import subprocess as _subprocess
    _original_popen_init = _subprocess.Popen.__init__

    def _no_window_popen_init(self, *args, **kwargs):
        kwargs["creationflags"] = kwargs.get("creationflags", 0) | _subprocess.CREATE_NO_WINDOW
        return _original_popen_init(self, *args, **kwargs)

    _subprocess.Popen.__init__ = _no_window_popen_init

import argparse
import ctypes
import queue
import re
import secrets
import shutil
import subprocess
import threading
import time
import base64
import urllib.request
import urllib.error
import json
import logging
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from logging.handlers import RotatingFileHandler

import comtypes
from pycaw.pycaw import AudioUtilities, IAudioMeterInformation
import pystray
from PIL import Image, ImageDraw
import yt_dlp

if sys.platform == "win32":
    import winreg
    from ctypes import wintypes

# ----------------------------------------------------------------------
# CONFIG - edit these to taste
# ----------------------------------------------------------------------
VLC_HOST = "localhost"          # VLC's web interface is only ever bound
                                 # to localhost - see ensure_vlc_ready()

THRESHOLD = 0.06                   # 0.0 - 1.0 peak level that counts as "sound"
CHECK_INTERVAL = 0.05              # seconds between volume checks
PAUSE_AFTER = 0.5                 # seconds of sustained sound before pausing
RESUME_AFTER = 0.6                 # seconds of sustained quiet before resuming
LOUD_HOLD = 0.5                    # treat sound as "still present" for this many
                                    # seconds after the last loud reading - smooths
                                    # over natural micro-gaps in a peak meter

FADE_TIME = 0.6                    # seconds to fade volume in/out, typically 0.5-1.0.
                                    # <= 0 always falls back to an instant cutoff,
                                    # regardless of the tray "Fade" toggle.
VLC_FULL_VOLUME = 256              # VLC's HTTP volume scale: 256 = 100%

EXCLUDE_PROCESS_NAMES = {"vlc.exe"}

DEBUG = False                      # prints/logs live peak readings
                                    # set to True again if you need to troubleshoot
# ----------------------------------------------------------------------

# Settings/config live next to the .exe once this is compiled with
# PyInstaller (onedir build), or next to this .py file when run from
# source - either way, "next to the running app" rather than some fixed
# install path, so a portable copy just works.
if getattr(sys, "frozen", False):
    BASE_DIR = os.path.dirname(sys.executable)
else:
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))


def resource_path(*parts):
    """Locates a bundled read-only resource (e.g. assets/icon.ico) rather
    than a writable config/settings file - these live in different places
    once frozen. PyInstaller's bootloader sets sys._MEIPASS to wherever it
    unpacked bundled data (the _internal folder, for a onedir build);
    unfrozen, it's just next to this script, same as BASE_DIR."""
    base = getattr(sys, "_MEIPASS", BASE_DIR) if getattr(sys, "frozen", False) else BASE_DIR
    return os.path.join(base, *parts)


SETTINGS_FILE = os.path.join(BASE_DIR, "auto_pauser_settings.json")
DEFAULT_SETTINGS = {"fade_enabled": True, "mute_mode": False, "desired_volume_percent": 100}

VLC_CONFIG_FILE = os.path.join(BASE_DIR, "vlc_config.json")
DEFAULT_VLC_CONFIG = {
    "vlc_path": r"C:\Program Files\VideoLAN\VLC\vlc.exe",
    "default_playlist": "",
    "http_port": 8080,
    "http_password": "",   # auto-generated on first run - see load_vlc_config()
    # Optional: name of a browser ("chrome", "firefox", "edge", "brave", ...)
    # that's currently logged into the streaming site(s) you use with
    # --launchVideoStream. When set, yt-dlp authenticates using that
    # browser's saved login/cookies instead of an anonymous request, which
    # is what lets it request an ad-free stream on sites/channels where your
    # subscription grants that benefit. Leave blank for anonymous requests.
    "ytdlp_cookies_from_browser": "",
}

LOG_FILE = os.path.join(BASE_DIR, "auto_pauser.log")

SINGLE_INSTANCE_MUTEX_NAME = "Global\\BGM_AutoPauser_SingleInstance"


# ----------------------------------------------------------------------
# Logging - only really matters once this is a --windowed frozen exe,
# where there's no console for print()/DEBUG output or an unhandled
# crash traceback to land on. Kept lightweight; disabled cleanly if the
# log file can't be created for some reason (e.g. a read-only folder).
# ----------------------------------------------------------------------
def _setup_logging():
    try:
        handler = RotatingFileHandler(LOG_FILE, maxBytes=1_000_000, backupCount=2, encoding="utf-8")
        handler.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(message)s"))
        root = logging.getLogger()
        root.setLevel(logging.DEBUG if DEBUG else logging.INFO)
        root.addHandler(handler)
    except OSError:
        pass


class _StreamToLogger:
    """Stand-in for sys.stdout/sys.stderr when frozen+windowed, where
    both are None and a bare print() would raise. Routes writes to the
    log file line-by-line instead."""

    def __init__(self, level):
        self.level = level
        self._buffer = ""

    def write(self, message):
        self._buffer += message
        while "\n" in self._buffer:
            line, self._buffer = self._buffer.split("\n", 1)
            if line.strip():
                logging.log(self.level, line)

    def flush(self):
        pass

    def isatty(self):
        return False


if getattr(sys, "frozen", False):
    _setup_logging()
    sys.stdout = _StreamToLogger(logging.INFO)
    sys.stderr = _StreamToLogger(logging.ERROR)
    logging.info("=== Auto-Pauser starting (frozen build) ===")


def load_settings():
    try:
        with open(SETTINGS_FILE, "r") as f:
            data = json.load(f)
        return {**DEFAULT_SETTINGS, **{k: data[k] for k in DEFAULT_SETTINGS if k in data}}
    except (FileNotFoundError, json.JSONDecodeError, OSError, ValueError):
        return dict(DEFAULT_SETTINGS)


def save_settings(settings):
    try:
        with open(SETTINGS_FILE, "w") as f:
            json.dump(settings, f, indent=2)
    except OSError as e:
        if DEBUG:
            print(f"[settings] failed to save: {e}")


# ----------------------------------------------------------------------
# VLC install-location + connection config
# ----------------------------------------------------------------------
def load_vlc_config():
    """Reads vlc_config.json next to the app, creating it with sane
    defaults on first run (including a freshly generated http_password)
    so there's nothing for the user to fill in before things work."""
    try:
        with open(VLC_CONFIG_FILE, "r") as f:
            data = json.load(f)
        cfg = {**DEFAULT_VLC_CONFIG, **{k: data[k] for k in DEFAULT_VLC_CONFIG if k in data}}
    except (FileNotFoundError, json.JSONDecodeError, OSError, ValueError):
        cfg = dict(DEFAULT_VLC_CONFIG)

    needs_save = not os.path.isfile(VLC_CONFIG_FILE)
    if not cfg.get("http_password"):
        cfg["http_password"] = secrets.token_hex(12)
        needs_save = True
    if needs_save:
        save_vlc_config(cfg)

    return cfg


def save_vlc_config(cfg):
    try:
        with open(VLC_CONFIG_FILE, "w") as f:
            json.dump(cfg, f, indent=2)
    except OSError as e:
        if DEBUG:
            print(f"[vlc_config] failed to save: {e}")


def _which_vlc():
    return shutil.which("vlc") or shutil.which("vlc.exe")


def _detect_vlc_via_registry():
    """VLC's installer writes its install folder to the registry - this is
    the most reliable way to find it regardless of drive/folder choice."""
    if sys.platform != "win32":
        return None
    reg_locations = [
        (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\VideoLAN\VLC"),
        (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\VideoLAN\VLC"),
        (winreg.HKEY_CURRENT_USER, r"SOFTWARE\VideoLAN\VLC"),
    ]
    for hive, subkey in reg_locations:
        try:
            with winreg.OpenKey(hive, subkey) as key:
                install_dir, _ = winreg.QueryValueEx(key, "InstallDir")
                candidate = os.path.join(install_dir, "vlc.exe")
                if os.path.isfile(candidate):
                    return candidate
        except OSError:
            continue
    return None


def _detect_vlc_via_common_paths():
    for candidate in (
        r"C:\Program Files\VideoLAN\VLC\vlc.exe",
        r"C:\Program Files (x86)\VideoLAN\VLC\vlc.exe",
    ):
        if os.path.isfile(candidate):
            return candidate
    return None


def resolve_vlc_path():
    """Priority: an explicit, still-valid path in vlc_config.json, then
    dynamic detection (PATH -> registry -> common install folders). A
    freshly detected path is written back to the json so it stays in sync
    if VLC gets reinstalled/moved. Returns None if nothing at all is found."""
    cfg = load_vlc_config()
    configured = (cfg.get("vlc_path") or "").strip()

    if configured and os.path.isfile(configured):
        return configured

    detected = _which_vlc() or _detect_vlc_via_registry() or _detect_vlc_via_common_paths()
    if detected:
        if detected != configured:
            cfg["vlc_path"] = detected
            save_vlc_config(cfg)
        return detected

    if configured:
        logging.warning(f"[vlc] configured vlc_path does not exist: {configured}")
        return configured  # let the launch attempt fail loudly/log it, rather than guess further

    logging.warning("[vlc] could not locate vlc.exe anywhere")
    return None


# ----------------------------------------------------------------------
# Playlist shortcuts - one .exe can only ever have one Start Menu shortcut
# with one fixed set of Arguments, so multiple looped-playlist "profiles"
# (e.g. one shortcut per music folder) need one shortcut each, each with
# its own --launchPlaylist. This builds those on demand from the tray menu:
# a small .bat under playlist-shortcuts/_bats/ that calls this app with the
# chosen playlist baked in, and a .lnk under playlist-shortcuts/ pointing at
# that .bat - so the shortcuts are easy to find, rename, or delete later
# without touching this app's own folder.
# ----------------------------------------------------------------------
SHORTCUTS_DIR = os.path.join(BASE_DIR, "playlist-shortcuts")
SHORTCUTS_BATS_DIR = os.path.join(SHORTCUTS_DIR, "_bats")

# Video-stream shortcuts - same idea as the playlist shortcuts above, but each
# points at a single stream URL via --launchVideoStream instead of a looped
# local folder via --launchPlaylist.
VIDEOSTREAM_SHORTCUTS_DIR = os.path.join(BASE_DIR, "videostream-shortcuts")
_STREAM_SHORTCUT_NAME_RE = re.compile(r'^StreamShortcut(\d+)$')

_INVALID_FILENAME_CHARS = re.compile(r'[<>:"/\\|?*\x00-\x1f]')


def _sanitize_filename(name):
    name = _INVALID_FILENAME_CHARS.sub("", name).strip()
    name = name.rstrip(" .")  # Windows disallows trailing dots/spaces in filenames
    return name or "Playlist"


def _unique_path(path):
    """Appends ' (2)', ' (3)', etc. if path already exists, rather than
    silently overwriting an existing same-named shortcut."""
    if not os.path.exists(path):
        return path
    base, ext = os.path.splitext(path)
    n = 2
    while True:
        candidate = f"{base} ({n}){ext}"
        if not os.path.exists(candidate):
            return candidate
        n += 1


def _ps_quote(value):
    """Single-quotes a value for embedding in a PowerShell script,
    doubling any embedded single quotes (PowerShell's own escape rule)."""
    return "'" + str(value).replace("'", "''") + "'"


def create_playlist_shortcut(playlist_dir, name):
    """Creates a direct .lnk shortcut pointing directly to the application
    executable with the --launchPlaylist argument included, bypassing the
    need for any intermediate .bat files."""
    os.makedirs(SHORTCUTS_DIR, exist_ok=True)

    safe_name = _sanitize_filename(name)
    lnk_path = _unique_path(os.path.join(SHORTCUTS_DIR, safe_name + ".lnk"))

    # Determine what the base application is (the compiled exe or python interpreter)
    target_exe = sys.executable
    if getattr(sys, "frozen", False):
        arguments = f'--launchPlaylist "{playlist_dir}"'
    else:
        # Running from source code (.py file)
        arguments = f'"{os.path.abspath(__file__)}" --launchPlaylist "{playlist_dir}"'

    ps_lines = [
        "$s = New-Object -ComObject WScript.Shell",
        f"$sc = $s.CreateShortcut({_ps_quote(lnk_path)})",
        f"$sc.TargetPath = {_ps_quote(target_exe)}",
        f"$sc.Arguments = {_ps_quote(arguments)}",
        f"$sc.WorkingDirectory = {_ps_quote(BASE_DIR)}",
        f"$sc.IconLocation = {_ps_quote(target_exe + ',0')}",
        "$sc.Save()",
    ]

    script = "\n".join(ps_lines)
    encoded = base64.b64encode(script.encode("utf-16-le")).decode("ascii")
    result = subprocess.run(
        ["powershell", "-NoProfile", "-NonInteractive", "-EncodedCommand", encoded],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or "PowerShell shortcut creation failed")

    return lnk_path


def _next_stream_shortcut_name():
    """Default name for a new video-stream shortcut: 'StreamShortcut1' if
    that's free, otherwise the lowest-numbered 'StreamShortcut<N>' that
    isn't already taken by an existing .lnk in videostream-shortcuts/."""
    existing_numbers = set()
    try:
        for fname in os.listdir(VIDEOSTREAM_SHORTCUTS_DIR):
            stem, ext = os.path.splitext(fname)
            if ext.lower() != ".lnk":
                continue
            m = _STREAM_SHORTCUT_NAME_RE.match(stem)
            if m:
                existing_numbers.add(int(m.group(1)))
    except OSError:
        pass  # folder doesn't exist yet - no existing shortcuts to avoid

    n = 1
    while n in existing_numbers:
        n += 1
    return f"StreamShortcut{n}"


def _is_valid_url(url):
    from urllib.parse import urlparse
    try:
        parsed = urlparse(url)
    except ValueError:
        return False
    return bool(parsed.scheme) and bool(parsed.netloc)


def create_videostream_shortcut(url, name, popout):
    """Creates a direct .lnk shortcut pointing at the application executable
    with --launchVideoStream (and optionally --popout) baked in, mirroring
    create_playlist_shortcut() above but for a single stream URL instead of
    a looped local folder."""
    os.makedirs(VIDEOSTREAM_SHORTCUTS_DIR, exist_ok=True)

    safe_name = _sanitize_filename(name)
    lnk_path = _unique_path(os.path.join(VIDEOSTREAM_SHORTCUTS_DIR, safe_name + ".lnk"))

    target_exe = sys.executable
    popout_suffix = " --popout" if popout else ""
    if getattr(sys, "frozen", False):
        arguments = f'--launchVideoStream "{url}"{popout_suffix}'
    else:
        # Running from source code (.py file)
        arguments = f'"{os.path.abspath(__file__)}" --launchVideoStream "{url}"{popout_suffix}'

    ps_lines = [
        "$s = New-Object -ComObject WScript.Shell",
        f"$sc = $s.CreateShortcut({_ps_quote(lnk_path)})",
        f"$sc.TargetPath = {_ps_quote(target_exe)}",
        f"$sc.Arguments = {_ps_quote(arguments)}",
        f"$sc.WorkingDirectory = {_ps_quote(BASE_DIR)}",
        f"$sc.IconLocation = {_ps_quote(target_exe + ',0')}",
        "$sc.Save()",
    ]

    script = "\n".join(ps_lines)
    encoded = base64.b64encode(script.encode("utf-16-le")).decode("ascii")
    result = subprocess.run(
        ["powershell", "-NoProfile", "-NonInteractive", "-EncodedCommand", encoded],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or "PowerShell shortcut creation failed")

    return lnk_path


def _reveal_in_explorer(path):
    try:
        # Correct form: /select, as its own token, path as the following argument.
        # Explorer's command-line parser is extremely picky; the old
        # f'/select,"{path}"' single-token form often fails and falls back
        # to the user's Documents folder.
        subprocess.run(["explorer", "/select,", os.path.normpath(path)], check=False)
    except Exception as e:
        if DEBUG:
            print(f"[shortcut] failed to open Explorer: {e}")


def _ask_shortcut_details(root, default_name):
    """Small modal dialog: shortcut name + "open its folder afterward" checkbox.
    Returns (name, open_location), or None if cancelled."""
    dialog = tk.Toplevel(root)
    dialog.title("New Playlist Shortcut")
    dialog.resizable(False, False)
    dialog.attributes("-topmost", True)
    result = {"value": None}

    tk.Label(dialog, text="Shortcut name:").grid(row=0, column=0, columnspan=2, sticky="w", padx=12, pady=(12, 0))
    name_var = tk.StringVar(value=default_name)
    entry = tk.Entry(dialog, textvariable=name_var, width=34)
    entry.grid(row=1, column=0, columnspan=2, padx=12, pady=(2, 10))
    entry.focus_set()
    entry.select_range(0, "end")

    open_location_var = tk.BooleanVar(value=True)
    tk.Checkbutton(dialog, text="Open Shortcut Location", variable=open_location_var).grid(
        row=2, column=0, columnspan=2, sticky="w", padx=12
    )

    def on_ok(event=None):
        result["value"] = (name_var.get().strip(), open_location_var.get())
        dialog.destroy()

    def on_cancel(event=None):
        result["value"] = None
        dialog.destroy()

    btns = tk.Frame(dialog)
    btns.grid(row=3, column=0, columnspan=2, pady=12)
    tk.Button(btns, text="Create", command=on_ok, width=10, default="active").pack(side="left", padx=5)
    tk.Button(btns, text="Cancel", command=on_cancel, width=10).pack(side="left", padx=5)

    dialog.bind("<Return>", on_ok)
    dialog.bind("<Escape>", on_cancel)
    dialog.protocol("WM_DELETE_WINDOW", on_cancel)

    dialog.update_idletasks()
    w, h = dialog.winfo_width(), dialog.winfo_height()
    sw, sh = dialog.winfo_screenwidth(), dialog.winfo_screenheight()
    dialog.geometry(f"+{(sw - w) // 2}+{(sh - h) // 2}")

    dialog.grab_set()
    dialog.wait_window()

    if not result["value"] or not result["value"][0]:
        return None
    return result["value"]


def _new_playlist_shortcut_flow(root):
    """Runs entirely on the Tk thread: folder picker -> name/checkbox dialog
    -> create the shortcut -> confirm, optionally opening Explorer with it
    selected (there's no reliable way to pin to Start programmatically
    anymore on modern Windows, so this is the one-click-away substitute)."""
    playlist_dir = filedialog.askdirectory(title="Choose the playlist folder for this shortcut", mustexist=True)
    if not playlist_dir:
        return
    playlist_dir = os.path.normpath(playlist_dir)

    details = _ask_shortcut_details(root, default_name=os.path.basename(playlist_dir) or "Playlist")
    if details is None:
        return
    name, open_location = details

    try:
        lnk_path = create_playlist_shortcut(playlist_dir, name)
    except Exception as e:
        logging.error(f"[shortcut] failed to create playlist shortcut: {e}")
        messagebox.showerror("Shortcut creation failed", f"Something went wrong:\n{e}")
        return

    if open_location:
        _reveal_in_explorer(lnk_path)


def _ask_videostream_shortcut_details(root, default_name):
    """Modal dialog: shortcut name, stream URL, and a '--popout' checkbox -
    laid out label-above-field like the reference screenshot. Returns
    (name, url, popout), or None if cancelled. The URL is validated before
    the dialog is allowed to close via OK."""
    dialog = tk.Toplevel(root)
    dialog.title("Add Video Stream Shortcut")
    dialog.resizable(False, False)
    dialog.attributes("-topmost", True)
    result = {"value": None}

    tk.Label(dialog, text="Name:").grid(row=0, column=0, sticky="w", padx=12, pady=(12, 2))
    name_var = tk.StringVar(value=default_name)
    name_entry = tk.Entry(dialog, textvariable=name_var, width=42)
    name_entry.grid(row=1, column=0, padx=12, pady=(0, 10), sticky="ew")

    tk.Label(dialog, text="Stream URL:").grid(row=2, column=0, sticky="w", padx=12)
    url_var = tk.StringVar()
    url_entry = tk.Entry(dialog, textvariable=url_var, width=42)
    url_entry.grid(row=3, column=0, padx=12, pady=(0, 10), sticky="ew")
    url_entry.focus_set()

    popout_var = tk.BooleanVar(value=False)
    tk.Checkbutton(dialog, text="Pop out video window (--popout)", variable=popout_var).grid(
        row=4, column=0, sticky="w", padx=12
    )

    error_var = tk.StringVar(value="")
    tk.Label(dialog, textvariable=error_var, fg="#d9534f").grid(
        row=5, column=0, sticky="w", padx=12, pady=(4, 0)
    )

    def on_ok(event=None):
        name = name_var.get().strip() or default_name
        url = url_var.get().strip()
        if not url or not _is_valid_url(url):
            error_var.set("Please enter a valid URL (e.g. https://...)")
            return
        result["value"] = (name, url, popout_var.get())
        dialog.destroy()

    def on_cancel(event=None):
        result["value"] = None
        dialog.destroy()

    btns = tk.Frame(dialog)
    btns.grid(row=6, column=0, pady=12)
    tk.Button(btns, text="OK", command=on_ok, width=10, default="active").pack(side="left", padx=5)
    tk.Button(btns, text="Cancel", command=on_cancel, width=10).pack(side="left", padx=5)

    dialog.bind("<Return>", on_ok)
    dialog.bind("<Escape>", on_cancel)
    dialog.protocol("WM_DELETE_WINDOW", on_cancel)

    dialog.update_idletasks()
    w, h = dialog.winfo_width(), dialog.winfo_height()
    sw, sh = dialog.winfo_screenwidth(), dialog.winfo_screenheight()
    dialog.geometry(f"+{(sw - w) // 2}+{(sh - h) // 2}")

    dialog.grab_set()
    dialog.wait_window()

    return result["value"]


def _new_videostream_shortcut_flow(root):
    """Runs entirely on the Tk thread: name/URL/popout dialog -> create the
    shortcut -> always reveal it in Explorer (unlike the playlist flow, this
    one has no 'open location' checkbox - it always opens per the spec)."""
    default_name = _next_stream_shortcut_name()
    details = _ask_videostream_shortcut_details(root, default_name)
    if details is None:
        return
    name, url, popout = details

    try:
        lnk_path = create_videostream_shortcut(url, name, popout)
    except Exception as e:
        logging.error(f"[shortcut] failed to create video stream shortcut: {e}")
        messagebox.showerror("Shortcut creation failed", f"Something went wrong:\n{e}")
        return

    _reveal_in_explorer(lnk_path)


def _resolve_stream_playback_url(url, vlc_cfg):
    """VLC has no built-in understanding of a page URL like
    twitch.tv/<channel> or a YouTube watch link - handing one of those to
    VLC directly just loads its idle "no media" cone with nothing playing,
    since VLC has nothing it recognises as a media demux for an HTML page.
    yt-dlp knows how to resolve that page into the actual direct
    HLS/DASH/etc. stream URL VLC *can* play.

    Falls back to the original URL unchanged if yt-dlp doesn't recognise it
    (e.g. the user already pasted a direct .m3u8/stream URL) or resolution
    fails for any reason (offline stream, network hiccup, site changes,
    etc.) - better to let VLC attempt the raw URL than give up entirely.

    If vlc_cfg["ytdlp_cookies_from_browser"] names a browser (e.g. "chrome",
    "firefox", "edge"), yt-dlp authenticates as whatever account is logged
    into that browser - lets it request the same ad-free stream your
    subscription would get you in the browser, on sites where the
    subscriber-ad-free benefit still applies. Requires actually being
    subscribed/eligible on that channel; not something we can force.
    """
    ydl_opts = {"quiet": True, "no_warnings": True, "format": "best", "noplaylist": True}
    cookies_browser = (vlc_cfg.get("ytdlp_cookies_from_browser") or "").strip()
    if cookies_browser:
        ydl_opts["cookiesfrombrowser"] = (cookies_browser,)
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
        if info and "entries" in info and info["entries"]:
            info = info["entries"][0]  # e.g. a channel page resolving to its live entry
        resolved = info.get("url") if info else None
        if resolved:
            logging.info(f"[vlc] resolved '{url}' to a direct playback URL via yt-dlp")
            return resolved
    except Exception as e:
        logging.warning(f"[vlc] yt-dlp couldn't resolve '{url}', using it as-is: {e}")
    return url


_POPOUT_WINDOW_SIZE = (480, 270)   # default pop-out size (16:9) - freely resizable afterward,
                                    # same as dragging any other window's border
_POPOUT_MARGIN = 24                # px from the screen edge


def _find_top_window_for_pid(pid, timeout=8.0, poll_interval=0.25):
    """Waits for and returns the HWND of the largest visible top-level
    window owned by the given process id - i.e. VLC's own main window,
    grabbed right after we launch it so it can be positioned/sized before
    the user even sees it appear wherever it last was. Returns None if
    nothing shows up in time (e.g. VLC failed to start)."""
    if sys.platform != "win32":
        return None

    user32 = ctypes.windll.user32
    deadline = time.time() + timeout

    def _collect_candidates():
        found = []

        @ctypes.WINFUNCTYPE(ctypes.c_bool, ctypes.c_void_p, ctypes.c_void_p)
        def _enum_proc(hwnd, _lparam):
            proc_pid = wintypes.DWORD()
            user32.GetWindowThreadProcessId(hwnd, ctypes.byref(proc_pid))
            if proc_pid.value == pid and user32.IsWindowVisible(hwnd):
                rect = wintypes.RECT()
                user32.GetWindowRect(hwnd, ctypes.byref(rect))
                area = max(0, rect.right - rect.left) * max(0, rect.bottom - rect.top)
                if area > 0:
                    found.append((area, hwnd))
            return True

        user32.EnumWindows(_enum_proc, 0)
        return found

    while time.time() < deadline:
        candidates = _collect_candidates()
        if candidates:
            candidates.sort(reverse=True)  # biggest window first - VLC's main window, not some tooltip
            return candidates[0][1]
        time.sleep(poll_interval)
    return None


def _apply_popout_geometry(pid):
    """Moves/resizes VLC's window into a small corner window - the same
    thing the user was otherwise doing by hand (drag to resize, Ctrl+H to
    hide controls) every single time. Runs in its own background thread so
    it doesn't block ensure_vlc_ready() while it waits for VLC's window to
    actually appear."""
    hwnd = _find_top_window_for_pid(pid)
    if not hwnd:
        logging.warning("[vlc] popout: never found VLC's window to resize/position")
        return

    user32 = ctypes.windll.user32
    screen_w = user32.GetSystemMetrics(0)
    screen_h = user32.GetSystemMetrics(1)
    width, height = _POPOUT_WINDOW_SIZE
    x = max(0, screen_w - width - _POPOUT_MARGIN)
    y = max(0, screen_h - height - _POPOUT_MARGIN)

    SWP_NOZORDER = 0x0004
    SWP_SHOWWINDOW = 0x0040
    user32.SetWindowPos(hwnd, None, x, y, width, height, SWP_NOZORDER | SWP_SHOWWINDOW)
    logging.info(f"[vlc] popout: positioned window at ({x}, {y}) size {width}x{height}")


def ensure_vlc_ready(controller, vlc_cfg, playlist=None, video_stream_url=None, popout=False):
    """Makes sure VLC is reachable over the HTTP interface, without ever
    touching VLC's own Preferences.

    If a working web interface is already reachable (matching password),
    VLC is left completely alone - covers the case where it's already
    running from a previous launch, or from a shortcut the user set up
    with matching --http-password/--http-port flags of their own.

    Otherwise, any running VLC is closed and a fresh one launched with
    the web interface baked into the command line
    (--extraintf http --http-password ... --http-port ...), so nothing
    needs to be configured by hand.
    """
    # Fast, single-shot check: "not reachable yet" is the normal case on a
    # cold start (VLC hasn't been launched yet at all), and this runs in the
    # background (see main()) - but keeping it quick still matters, since a
    # slow answer here delays the taskkill+relaunch decision either way.
    if controller.status(retries=0, timeout=0.75) is not None:
        logging.info("[vlc] web interface already reachable - leaving the running VLC alone")
        return

    vlc_path = resolve_vlc_path()

    try:
        subprocess.run(
            ["taskkill", "/f", "/im", "vlc.exe"],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )
    except Exception as e:
        if DEBUG:
            print(f"[vlc] taskkill failed (probably wasn't running): {e}")
    time.sleep(0.5)

    if not vlc_path:
        logging.error("[vlc] no VLC install found - can't launch it. "
                       "Set \"vlc_path\" in vlc_config.json manually.")
        return

    launch_args = [
        vlc_path,
        "--extraintf", "http",
        "--http-host", VLC_HOST,
        "--http-port", str(vlc_cfg.get("http_port", 8080)),
        "--http-password", vlc_cfg.get("http_password", ""),
    ]

    if video_stream_url:
        # Windowed and visible in the taskbar (no --qt-start-minimized) -
        # this is a live stream the user presumably wants to actually watch,
        # not background music.
        #
        # --no-qt-video-autoresize/--autoscale apply regardless of --popout:
        # VLC's default behaviour is to snap its window back to the video's
        # *native* resolution any time that resolution changes (e.g. an ad
        # break creative at a different resolution than the stream) - that's
        # what was resetting a manually-resized window back to full size.
        # Disabling autoresize + scaling the video to fit the window instead
        # keeps whatever size the window actually is.
        launch_args += ["--no-qt-video-autoresize", "--autoscale"]
        if popout:
            # --video-on-top and --qt-minimal-view are both genuine VLC
            # options - on-top pins the window above others, minimal-view is
            # the command-line equivalent of the Ctrl+H shortcut (hides the
            # menu bar/toolbar/controls). Neither one, by itself, sets an
            # initial size or position though - that's handled below via
            # _apply_popout_geometry() once the window actually exists,
            # since VLC has no command-line flag for that part.
            launch_args += ["--video-on-top", "--qt-minimal-view"]
        launch_args += [_resolve_stream_playback_url(video_stream_url, vlc_cfg)]
    else:
        launch_args += ["--qt-start-minimized"]
        if playlist:
            launch_args += ["--loop", playlist]

    try:
        proc = subprocess.Popen(launch_args)
        logging.info(
            f"[vlc] launched with web interface enabled "
            f"(playlist={playlist!r}, video_stream_url={video_stream_url!r}, popout={popout})"
        )
        if video_stream_url and popout:
            threading.Thread(target=_apply_popout_geometry, args=(proc.pid,), daemon=True).start()
    except OSError as e:
        logging.error(f"[vlc] failed to launch '{vlc_path}': {e}")


# ----------------------------------------------------------------------
# Single instance - relaunching the shortcut (e.g. with a different
# --launchPlaylist) should behave like a clean restart, not stack up a
# second tray icon and a second audio-watching loop.
# ----------------------------------------------------------------------
def ensure_single_instance():
    if sys.platform != "win32":
        return None

    kernel32 = ctypes.windll.kernel32
    mutex = kernel32.CreateMutexW(None, False, SINGLE_INSTANCE_MUTEX_NAME)
    ERROR_ALREADY_EXISTS = 183
    if ctypes.GetLastError() == ERROR_ALREADY_EXISTS:
        try:
            if getattr(sys, "frozen", False):
                # The frozen exe has a distinctive process image name, so a
                # plain taskkill-by-name (excluding our own new PID) works.
                exe_name = os.path.basename(sys.executable)
                subprocess.run(
                    ["taskkill", "/f", "/im", exe_name, "/fi", f"PID ne {os.getpid()}"],
                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                )
            else:
                # Running from source, the process image name is just
                # "python.exe" - too generic to taskkill by name safely (it'd
                # risk killing unrelated Python processes). Match by command
                # line instead, same approach the old run_auto_pauser.bat used.
                script_name = os.path.basename(__file__)
                ps_cmd = (
                    f"Get-CimInstance Win32_Process -Filter \"CommandLine LIKE '%{script_name}%'\" "
                    f"| Where-Object ProcessId -ne {os.getpid()} | Remove-CimInstance"
                )
                subprocess.run(
                    ["powershell", "-NoProfile", "-Command", ps_cmd],
                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                )
        except Exception as e:
            if DEBUG:
                print(f"[instance] failed to close previous instance: {e}")
        time.sleep(1)
    return mutex  # kept referenced for the process lifetime; not otherwise used


class VLCController:
    """Talks to VLC's built-in HTTP interface."""

    def __init__(self, host, port, password):
        self.base_url = f"http://{host}:{port}/requests"
        auth = base64.b64encode(f":{password}".encode()).decode()
        self.headers = {"Authorization": f"Basic {auth}"}

    def _get(self, path, retries=1, timeout=3.0):
        req = urllib.request.Request(self.base_url + path, headers=self.headers)
        for attempt in range(retries + 1):
            try:
                with urllib.request.urlopen(req, timeout=timeout) as resp:
                    data = resp.read()
                    if DEBUG:
                        print(f"[vlc] GET {path} -> HTTP {resp.status}")
                    return data
            except urllib.error.HTTPError as e:
                if DEBUG:
                    print(f"[vlc] HTTP error {e.code} for {path}")
                return None
            except (urllib.error.URLError, ConnectionError, TimeoutError) as e:
                if DEBUG:
                    print(f"[vlc] connection error for {path} (attempt {attempt + 1}): {e}")
        return None

    def _status_dict(self, retries=1, timeout=3.0):
        data = self._get("/status.json", retries=retries, timeout=timeout)
        if data is None:
            return None
        try:
            return json.loads(data)
        except json.JSONDecodeError:
            if DEBUG:
                print("[vlc] failed to parse status response")
            return None

    def status(self, retries=1, timeout=3.0):
        """Returns 'playing', 'paused', 'stopped', or None if VLC/web iface unreachable.
        retries/timeout are overridable - ensure_vlc_ready() uses a fast, single-shot
        check since "not reachable yet" is the common case on a cold start and
        shouldn't block the tray icon from appearing while it waits this out."""
        d = self._status_dict(retries=retries, timeout=timeout)
        return d.get("state") if d else None

    def get_volume(self):
        """Returns the current volume on VLC's 0-256(+) scale, or None if unreachable."""
        d = self._status_dict()
        if d and "volume" in d:
            return d["volume"]
        return None

    def set_volume(self, val):
        val = max(0, int(round(val)))
        self._get(f"/status.json?command=volume&val={val}")

    def pause(self):
        st = self.status()
        if DEBUG:
            print(f"[vlc] pause() called - current VLC status: {st}")
        if st == "playing":
            self._get("/status.json?command=pl_forcepause")

    def play(self):
        st = self.status()
        if DEBUG:
            print(f"[vlc] play() called - current VLC status: {st}")
        if st == "paused":
            self._get("/status.json?command=pl_forceresume")


def get_other_audio_peak():
    """Returns the max peak level (0.0-1.0) across all sessions except excluded ones."""
    peak = 0.0
    try:
        sessions = AudioUtilities.GetAllSessions()
    except Exception as e:
        if DEBUG:
            print(f"[debug] GetAllSessions failed: {e}")
        return 0.0

    for session in sessions:
        if session.Process is None:
            continue
        name = session.Process.name().lower()
        if name in EXCLUDE_PROCESS_NAMES:
            continue
        try:
            meter = session._ctl.QueryInterface(IAudioMeterInformation)
            level = meter.GetPeakValue()
            if level > peak:
                peak = level
        except Exception as e:
            if DEBUG:
                print(f"[debug] peak read failed for {name}: {e}")
            continue
    return peak


class AutoPauser:
    def __init__(self, vlc_controller: "VLCController", force_mute_mode=False):
        self.vlc = vlc_controller
        self.enabled = True

        settings = load_settings()
        self.fade_enabled = settings["fade_enabled"]

        # force_mute_mode is set when launched with --launchVideoStream: live
        # streams should always be muted rather than paused (see module
        # docstring / tray menu). self._user_mute_mode tracks the user's
        # actual saved preference underneath the forced override, so a later
        # --launchPlaylist run still sees whatever the user last set by hand,
        # never the forced value from a stream session.
        self._user_mute_mode = settings["mute_mode"]
        self.force_mute_mode = force_mute_mode
        self.mute_mode = True if force_mute_mode else self._user_mute_mode

        # Single source of truth for "what volume VLC should be at when
        # nothing is ducking/fading it" - a plain 0-100 value owned entirely
        # by this app, never read back from VLC. The previous approach
        # re-read VLC's own live volume via vlc.get_volume() every time a
        # duck began (and again on manual disable()), which is exactly what
        # caused the reported bug: that live value is whatever the fade/mute
        # logic itself most recently drove it to (including mid-fade, or
        # already-muted, values like 6% or 0), not the user's real target.
        # Now it only ever changes in response to the user - via the tray
        # volume slider (see set_desired_volume_percent) or from whatever
        # was persisted last session - and duck/undock always target this
        # value instead of asking VLC what it currently thinks the volume is.
        self.desired_volume_percent = max(0, min(100, settings.get("desired_volume_percent", 100)))

        self._stop = False
        self._sound_since = None
        self._quiet_since = None
        self._last_loud_at = None

        self._ducked = False           # True while paused/muted by us
        self._fade_state = None        # None, "out", or "in"
        self._fade_start_time = None
        self._fade_start_vol = None

    def _save_settings(self):
        mute_to_save = self._user_mute_mode if self.force_mute_mode else self.mute_mode
        save_settings({
            "fade_enabled": self.fade_enabled,
            "mute_mode": mute_to_save,
            "desired_volume_percent": self.desired_volume_percent,
        })

    def _desired_vlc_volume(self):
        """Converts the persisted 0-100 desired_volume_percent into VLC's
        native 0-256(+) volume scale."""
        return self.desired_volume_percent / 100 * VLC_FULL_VOLUME

    def get_desired_volume_percent(self):
        """What the tray volume slider should display. Deliberately never
        reads VLC's live volume - while ducked (muted, or faded/paused
        toward 0) that live value is 0 or mid-fade, not the user's real
        target."""
        return self.desired_volume_percent

    def set_desired_volume_percent(self, percent):
        """Called from the tray volume slider (and once at startup to sync
        a saved volume onto a freshly launched VLC). Always updates and
        persists the stored target. Only pushed to VLC immediately if
        playback isn't currently ducked or mid-fade - if it is, the new
        value simply becomes what gets applied next time it un-ducks,
        rather than either briefly making a muted stream audible or getting
        silently overwritten by the next fade tick."""
        self.desired_volume_percent = max(0, min(100, percent))
        self._save_settings()
        if not self._ducked and self._fade_state is None:
            self.vlc.set_volume(self._desired_vlc_volume())

    def loop(self):
        # pycaw talks to Windows' COM-based audio API, which requires each
        # thread that uses it to initialize its own COM apartment - without
        # this, calls made from this background thread fail silently and
        # get_other_audio_peak() would always report 0.
        comtypes.CoInitialize()
        try:
            while not self._stop:
                if self.enabled:
                    self._tick()
                time.sleep(CHECK_INTERVAL)
        finally:
            comtypes.CoUninitialize()

    def _fade_is_effective(self):
        return self.fade_enabled and FADE_TIME > 0

    def _begin_duck(self):
        """Start pausing/muting - either straight away, or by kicking off a fade-out."""
        if DEBUG:
            action = "muting" if self.mute_mode else "pausing"
            print(f"[auto-pauser] threshold sustained -> {action}")

        if self._fade_is_effective():
            self._fade_state = "out"
            self._fade_start_time = time.time()
            # Fades from the desired target, not from whatever VLC's live
            # volume happens to read right now - see desired_volume_percent.
            self._fade_start_vol = self._desired_vlc_volume()
        else:
            if self.mute_mode:
                self.vlc.set_volume(0)
            else:
                self.vlc.pause()

        self._ducked = True

    def _begin_undock(self):
        """Start resuming/unmuting - either straight away, or by kicking off a fade-in."""
        if DEBUG:
            action = "unmuting" if self.mute_mode else "resuming"
            print(f"[auto-pauser] quiet sustained -> {action}")

        if not self.mute_mode:
            # Playback needs to actually resume before/while the volume ramps
            # back up - otherwise there's nothing to fade in.
            self.vlc.play()

        if self._fade_is_effective():
            self._fade_state = "in"
            self._fade_start_time = time.time()
            self._fade_start_vol = 0
        elif self.mute_mode:
            self.vlc.set_volume(self._desired_vlc_volume())
        # non-mute, non-fade: pause()/play() alone already covers it.

        self._ducked = False

    def _advance_fade(self, now):
        elapsed = now - self._fade_start_time
        progress = min(1.0, elapsed / FADE_TIME)
        # Read fresh each tick (rather than snapshotted once) so a volume
        # change made mid-fade via the tray slider is picked up immediately
        # instead of being overwritten once the fade finishes.
        target = self._desired_vlc_volume()

        if self._fade_state == "out":
            vol = self._fade_start_vol * (1 - progress)
            self.vlc.set_volume(vol)
            if progress >= 1.0:
                self.vlc.set_volume(0)
                if not self.mute_mode:
                    self.vlc.pause()
                self._fade_state = None
        elif self._fade_state == "in":
            vol = target * progress
            self.vlc.set_volume(vol)
            if progress >= 1.0:
                self.vlc.set_volume(target)
                self._fade_state = None

    def _tick(self):
        peak = get_other_audio_peak()
        now = time.time()

        if DEBUG:
            self._debug_counter = getattr(self, "_debug_counter", 0) + 1
            if self._debug_counter % 10 == 0:  # roughly every ~1.5s
                bar = "#" * int(peak * 40)
                print(f"peak={peak:.3f} threshold={THRESHOLD} {bar}")

        if peak >= THRESHOLD:
            self._last_loud_at = now

        is_loud = self._last_loud_at is not None and (now - self._last_loud_at) <= LOUD_HOLD

        if self._fade_state is not None:
            self._advance_fade(now)

        if is_loud:
            self._quiet_since = None
            if self._sound_since is None:
                self._sound_since = now
            elif (
                not self._ducked
                and self._fade_state is None
                and (now - self._sound_since) >= PAUSE_AFTER
            ):
                self._begin_duck()
        else:
            self._sound_since = None
            if self._quiet_since is None:
                self._quiet_since = now
            elif (
                self._ducked
                and self._fade_state is None
                and (now - self._quiet_since) >= RESUME_AFTER
            ):
                self._begin_undock()

    def stop(self):
        self._stop = True

    def disable(self):
        """Manual 'Enabled' toggle turning OFF - stops the watcher AND
        immediately pauses/mutes VLC's current track, so switching this off
        actually silences things instead of leaving the watcher's last state
        in place until something happens to change it."""
        self.enabled = False
        self._fade_state = None
        if self.mute_mode:
            # No get_volume() read here on purpose - if this fires while
            # already auto-ducked (VLC's live volume sitting at 0, or
            # mid-fade), that read used to silently overwrite the real
            # target with whatever VLC happened to be at. desired_volume_percent
            # is untouched either way, so re-enabling always restores correctly.
            self.vlc.set_volume(0)
        else:
            self.vlc.pause()
        self._ducked = True

    def enable(self):
        """Manual 'Enabled' toggle turning back ON - resumes/unmutes VLC
        immediately and resets the watcher's timers so it starts fresh (if
        other audio is still loud, it'll naturally re-pause within
        PAUSE_AFTER seconds, same as any other time it detects noise)."""
        self.enabled = True
        self._sound_since = None
        self._quiet_since = None
        self._last_loud_at = None
        self._fade_state = None
        if self.mute_mode:
            self.vlc.set_volume(self._desired_vlc_volume())
        else:
            self.vlc.play()
        self._ducked = False


def make_icon_image(color):
    img = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.ellipse((8, 8, 56, 56), fill=color)
    return img


def _load_tray_icon_images():
    """Loads the app's own icon (assets/icon.ico - the same file used for
    the .exe's own icon in the .spec) for the tray, deriving a dimmed
    grayscale version for the "disabled" state from it. Falls back to a
    plain drawn dot if the asset is missing - e.g. running from source
    without an assets/ folder next to the script, or a build made before
    the asset existed - so a missing icon never crashes the app."""
    icon_path = resource_path("assets", "icon.ico")
    try:
        base = Image.open(icon_path).convert("RGBA")
    except (FileNotFoundError, OSError) as e:
        logging.warning(f"[tray] couldn't load {icon_path}, using fallback icon: {e}")
        return make_icon_image((40, 180, 99, 255)), make_icon_image((150, 150, 150, 255))

    dimmed = base.convert("L").convert("RGBA")
    dimmed.putalpha(base.split()[3])  # keep the original transparency mask
    return base, dimmed


# ----------------------------------------------------------------------
# Volume slider popup
# ----------------------------------------------------------------------
# A right-click tray menu can only ever hold text items/checkboxes - Windows'
# shell context menus have no slider control, so "a slider in the tray" is
# actually a small standalone window that appears next to where you clicked,
# same trick Windows' own volume/brightness flyouts use. It needs a Tk
# mainloop, which has to run on the main thread - so pystray's message loop
# (normally the thing blocking main()) is moved to a background thread
# instead, and the two talk to each other via a thread-safe queue rather
# than calling into Tk directly from pystray's thread.
_VOLUME_POPUP_SIZE = (220, 78)


def _get_cursor_pos():
    pt = wintypes.POINT()
    ctypes.windll.user32.GetCursorPos(ctypes.byref(pt))
    return pt.x, pt.y


def _show_volume_popup(root, pauser: "AutoPauser"):
    # Reads/writes the app's own desired_volume_percent, never VLC's live
    # volume - see AutoPauser.set_desired_volume_percent for why. This is
    # what lets the slider be dragged to set a new target while playback is
    # currently muted/paused by the auto-pauser, instead of showing (and
    # fighting with) whatever momentary 0%/mid-fade value VLC is actually at.
    percent = pauser.get_desired_volume_percent()

    popup = tk.Toplevel(root)
    popup.overrideredirect(True)      # no titlebar/border - this is a flyout, not a window
    popup.attributes("-topmost", True)
    popup.configure(bg="#2b2b2b")

    width, height = _VOLUME_POPUP_SIZE
    cursor_x, cursor_y = _get_cursor_pos()
    x = max(0, cursor_x - width // 2)
    y = max(0, cursor_y - height - 12)  # open above the click, like the menu that spawned it
    popup.geometry(f"{width}x{height}+{x}+{y}")

    tk.Label(
        popup, text="VLC Volume", fg="white", bg="#2b2b2b", font=("Segoe UI", 9)
    ).pack(pady=(8, 0))

    pct_var = tk.StringVar(value=f"{percent}%")
    last_sent_at = [0.0]
    MIN_SEND_INTERVAL = 0.05  # throttle mid-drag HTTP calls to ~20/sec

    def send_volume(pct):
        pauser.set_desired_volume_percent(pct)

    def on_change(raw_value):
        pct = int(float(raw_value))
        pct_var.set(f"{pct}%")
        now = time.time()
        if now - last_sent_at[0] >= MIN_SEND_INTERVAL:
            send_volume(pct)
            last_sent_at[0] = now

    def on_release(_event):
        send_volume(int(float(scale.get())))  # make sure the final position always lands

    row = tk.Frame(popup, bg="#2b2b2b")
    row.pack(padx=16, pady=(4, 0), fill="x")

    scale = ttk.Scale(row, from_=0, to=100, orient="horizontal", command=on_change, length=150)
    scale.set(percent)
    scale.pack(side="left", fill="x", expand=True)
    scale.bind("<ButtonRelease-1>", on_release)

    tk.Label(row, textvariable=pct_var, fg="white", bg="#2b2b2b", font=("Segoe UI", 9), width=4).pack(
        side="left", padx=(6, 0)
    )

    # Clicking elsewhere closes it, same as any other flyout
    popup.bind("<FocusOut>", lambda e: popup.destroy())
    popup.focus_force()


def _tk_ui_loop(ui_queue: "queue.Queue", pauser: AutoPauser):
    """Runs on the main thread. Owns the (hidden) Tk root and processes
    requests - opening the volume popup, shutting down - posted from the
    pystray thread via ui_queue, so pystray's own thread never touches
    Tk objects directly."""
    root = tk.Tk()
    root.withdraw()  # this root window itself is never shown - only its Toplevel popups are

    def poll_queue():
        try:
            while True:
                msg = ui_queue.get_nowait()
                if msg == "volume":
                    _show_volume_popup(root, pauser)
                elif msg == "new_shortcut":
                    _new_playlist_shortcut_flow(root)
                elif msg == "new_video_stream_shortcut":
                    _new_videostream_shortcut_flow(root)
                elif msg == "quit":
                    root.quit()
                    return
        except queue.Empty:
            pass
        root.after(100, poll_queue)

    root.after(100, poll_queue)
    root.mainloop()


def run_tray(pauser: AutoPauser, ui_queue: "queue.Queue"):
    icon_on, icon_off = _load_tray_icon_images()

    def toggle_enabled(icon, item):
        if pauser.enabled:
            pauser.disable()
        else:
            pauser.enable()
        icon.icon = icon_on if pauser.enabled else icon_off
        icon.title = "Auto-Pauser: ON" if pauser.enabled else "Auto-Pauser: OFF (paused)"

    def toggle_fade(icon, item):
        pauser.fade_enabled = not pauser.fade_enabled
        pauser._save_settings()

    def toggle_mute_mode(icon, item):
        if pauser.force_mute_mode:
            return  # greyed out in the menu already; belt-and-braces here too
        pauser.mute_mode = not pauser.mute_mode
        pauser._user_mute_mode = pauser.mute_mode
        pauser._save_settings()

    def open_volume(icon, item):
        ui_queue.put("volume")

    def new_shortcut(icon, item):
        ui_queue.put("new_shortcut")

    def new_video_stream_shortcut(icon, item):
        ui_queue.put("new_video_stream_shortcut")

    def quit_app(icon, item):
        pauser.stop()
        icon.stop()
        ui_queue.put("quit")

    def quit_app_and_vlc(icon, item):
        try:
            subprocess.run(
                ["taskkill", "/f", "/im", "vlc.exe"],
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            )
        except Exception as e:
            if DEBUG:
                print(f"[quit] failed to close VLC: {e}")
        pauser.stop()
        icon.stop()
        ui_queue.put("quit")

    icon = pystray.Icon(
        "auto_pauser",
        icon_on,
        "Auto-Pauser: ON",
        menu=pystray.Menu(
            pystray.MenuItem(
                "Enabled",
                toggle_enabled,
                checked=lambda item: pauser.enabled,
            ),
            pystray.MenuItem(
                "Fade in/out",
                toggle_fade,
                checked=lambda item: pauser.fade_enabled,
            ),
            pystray.MenuItem(
                "Mute instead of pause",
                toggle_mute_mode,
                checked=lambda item: pauser.mute_mode,
                enabled=lambda item: not pauser.force_mute_mode,
            ),
            pystray.MenuItem("Volume...", open_volume),
            pystray.MenuItem("New Playlist Shortcut...", new_shortcut),
            pystray.MenuItem("Add Video Stream Shortcut...", new_video_stream_shortcut),
            pystray.Menu.SEPARATOR,
            pystray.MenuItem("Quit", quit_app),
            pystray.MenuItem("Close BGM-AutoPause && VLC", quit_app_and_vlc),
        ),
    )
    icon.run()


def parse_args():
    parser = argparse.ArgumentParser(description="BGM Auto-Pauser for VLC")
    parser.add_argument(
        "--launchPlaylist",
        dest="playlist",
        default=None,
        help="Optional folder VLC should open (looped, minimized) on startup.",
    )
    parser.add_argument(
        "--launchVideoStream",
        dest="video_stream",
        default=None,
        help="Optional stream URL VLC should open windowed (visible in the "
             "taskbar) on startup, instead of a looped/minimized playlist.",
    )
    parser.add_argument(
        "--popout",
        dest="popout",
        action="store_true",
        help="Used with --launchVideoStream: opens the stream in a "
             "sizeable, always-on-top popped-out window.",
    )
    args, _unknown = parser.parse_known_args()
    return args


def _sync_initial_volume_once_ready(pauser: "AutoPauser", controller: "VLCController", timeout=15.0):
    """Waits for VLC's web interface to come up, then applies whatever
    desired_volume_percent was loaded/persisted from last session. This is
    what makes a saved volume below 100% actually take effect on a fresh
    launch, instead of leaving VLC at whatever it started at (usually full
    volume) until the next duck/undock cycle happens to touch it. If
    playback has already been ducked by the time this runs (e.g. other
    audio was already loud at startup), set_desired_volume_percent skips
    the live push on its own, same as a slider drag would."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        if controller.status(retries=0, timeout=0.75) is not None:
            pauser.set_desired_volume_percent(pauser.get_desired_volume_percent())
            return
        time.sleep(0.5)


def main():
    args = parse_args()

    # Relaunching the shortcut (possibly with a different playlist) should
    # behave like a clean restart rather than piling up tray icons.
    ensure_single_instance()

    vlc_cfg = load_vlc_config()
    controller = VLCController(VLC_HOST, vlc_cfg.get("http_port", 8080), vlc_cfg.get("http_password", ""))

    video_stream_url = (args.video_stream or "").strip() or None
    # --launchPlaylist and --launchVideoStream are mutually exclusive; a
    # stream URL (if given) takes priority since it's the more specific of
    # the two launch modes.
    playlist = None if video_stream_url else (args.playlist or vlc_cfg.get("default_playlist") or "").strip() or None
    popout = bool(args.popout) and video_stream_url is not None

    # This used to run inline here, which meant nothing appeared - no tray
    # icon, nothing - until VLC was confirmed reachable or relaunched. Now it
    # runs alongside everything else: the tray icon and pauser loop show up
    # immediately, and VLC calls the pauser loop makes in the meantime just
    # get "unreachable" (None) until this finishes, same as it already
    # handles any other time VLC isn't responding yet.
    threading.Thread(
        target=ensure_vlc_ready,
        args=(controller, vlc_cfg, playlist, video_stream_url, popout),
        daemon=True,
    ).start()

    # Launched via --launchVideoStream -> force mute-instead-of-pause for
    # this session only (see AutoPauser.__init__ / module docstring).
    pauser = AutoPauser(controller, force_mute_mode=video_stream_url is not None)
    t = threading.Thread(target=pauser.loop, daemon=True)
    t.start()

    threading.Thread(
        target=_sync_initial_volume_once_ready,
        args=(pauser, controller),
        daemon=True,
    ).start()

    # pystray's message loop and Tk's mainloop each need to own a thread of
    # their own; Tk needs the main thread, so pystray's runs in the
    # background instead, coordinating through ui_queue (see run_tray/_tk_ui_loop).
    ui_queue = queue.Queue()
    tray_thread = threading.Thread(target=run_tray, args=(pauser, ui_queue), daemon=True)
    tray_thread.start()

    _tk_ui_loop(ui_queue, pauser)
    sys.exit(0)


if __name__ == "__main__":
    main()